task: 'zju_mocap'
subject: 'p393'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_393_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_393_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_393_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_393_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_393_test'

resize_img_scale: 2
dataset_path: '/root/workspace-NerfHuman/CVPRversionAnimateHuman/dataset/zju_mocap/393_mono_train'
