task: 'zju_mocap'
subject: 'p392'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_392_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_392_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_392_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_392_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_392_test'

resize_img_scale: 0.5
dataset_path: '/root/workspace-NerfHuman/CVPRversionAnimateHuman/dataset/zju_mocap/392_mono_train'
