task: 'people-snapshot'
subject: 'male_3_casual'
experiment: 'single_gpu'
sex: 'male'
load_net: latest # the name of saved model when resuming the training

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'm3c_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'm3c_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'm3c_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'm3c_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'm3c_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
max_frame: 540

