task: 'zju_mocap'
subject: 'p387'
experiment: 'single_gpu'
num_train_frame: '387'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_train'
  num_train_frame: '387'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test'
  num_train_frame: '387'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_387_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_387_test'
  num_train_frame: '387'

resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
max_frame: 540

