task: 'zju_mocap'
subject: 'p394'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_394_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_394_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_394_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_394_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_394_test'


resize_img_scale: 2
dataset_path: '/root/workspace-NerfHuman/CVPRversionAnimateHuman/dataset/zju_mocap/394_mono_train'
